/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as ProtectedOrgRouteImport } from './routes/_protected/_org'
import { Route as ProtectedOnboardingRouteImport } from './routes/_protected/onboarding'
import { Route as ProtectedOrgIndexRouteImport } from './routes/_protected/_org/index'
import { Route as ProtectedOrgSettingsRouteRouteImport } from './routes/_protected/_org/settings/route'
import { Route as ProtectedAcceptInvitationIdRouteImport } from './routes/_protected/accept-invitation.$id'
import { Route as ProtectedOrgCatalogIndexRouteImport } from './routes/_protected/_org/catalog/index'
import { Route as ProtectedOrgCatalogIdRouteImport } from './routes/_protected/_org/catalog/$id'
import { Route as ProtectedOrgChatChatIdRouteImport } from './routes/_protected/_org/chat/$chatId'
import { Route as ProtectedOrgChatNewRouteImport } from './routes/_protected/_org/chat/new'
import { Route as ProtectedOrgSettingsIndexRouteImport } from './routes/_protected/_org/settings/index'
import { Route as ProtectedOrgSettingsGeneralRouteImport } from './routes/_protected/_org/settings/general'
import { Route as ProtectedOrgSettingsMembersRouteImport } from './routes/_protected/_org/settings/members'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedOrgRoute = ProtectedOrgRouteImport.update({
  id: '/_org',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOnboardingRoute = ProtectedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedOrgIndexRoute = ProtectedOrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedOrgRoute,
} as any)
const ProtectedOrgSettingsRouteRoute =
  ProtectedOrgSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedOrgRoute,
  } as any)
const ProtectedAcceptInvitationIdRoute =
  ProtectedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrgCatalogIndexRoute =
  ProtectedOrgCatalogIndexRouteImport.update({
    id: '/catalog/',
    path: '/catalog/',
    getParentRoute: () => ProtectedOrgRoute,
  } as any)
const ProtectedOrgCatalogIdRoute = ProtectedOrgCatalogIdRouteImport.update({
  id: '/catalog/$id',
  path: '/catalog/$id',
  getParentRoute: () => ProtectedOrgRoute,
} as any)
const ProtectedOrgChatChatIdRoute = ProtectedOrgChatChatIdRouteImport.update({
  id: '/chat/$chatId',
  path: '/chat/$chatId',
  getParentRoute: () => ProtectedOrgRoute,
} as any)
const ProtectedOrgChatNewRoute = ProtectedOrgChatNewRouteImport.update({
  id: '/chat/new',
  path: '/chat/new',
  getParentRoute: () => ProtectedOrgRoute,
} as any)
const ProtectedOrgSettingsIndexRoute =
  ProtectedOrgSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProtectedOrgSettingsRouteRoute,
  } as any)
const ProtectedOrgSettingsGeneralRoute =
  ProtectedOrgSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => ProtectedOrgSettingsRouteRoute,
  } as any)
const ProtectedOrgSettingsMembersRoute =
  ProtectedOrgSettingsMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => ProtectedOrgSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedOrgIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/settings': typeof ProtectedOrgSettingsRouteRouteWithChildren
  '/accept-invitation/$id': typeof ProtectedAcceptInvitationIdRoute
  '/catalog/$id': typeof ProtectedOrgCatalogIdRoute
  '/chat/$chatId': typeof ProtectedOrgChatChatIdRoute
  '/chat/new': typeof ProtectedOrgChatNewRoute
  '/settings/general': typeof ProtectedOrgSettingsGeneralRoute
  '/settings/members': typeof ProtectedOrgSettingsMembersRoute
  '/catalog/': typeof ProtectedOrgCatalogIndexRoute
  '/settings/': typeof ProtectedOrgSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedOrgIndexRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/signup': typeof AuthSignupRoute
  '/onboarding': typeof ProtectedOnboardingRoute
  '/accept-invitation/$id': typeof ProtectedAcceptInvitationIdRoute
  '/catalog/$id': typeof ProtectedOrgCatalogIdRoute
  '/chat/$chatId': typeof ProtectedOrgChatChatIdRoute
  '/chat/new': typeof ProtectedOrgChatNewRoute
  '/settings/general': typeof ProtectedOrgSettingsGeneralRoute
  '/settings/members': typeof ProtectedOrgSettingsMembersRoute
  '/catalog': typeof ProtectedOrgCatalogIndexRoute
  '/settings': typeof ProtectedOrgSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_protected/_org': typeof ProtectedOrgRouteWithChildren
  '/_protected/onboarding': typeof ProtectedOnboardingRoute
  '/_protected/_org/settings': typeof ProtectedOrgSettingsRouteRouteWithChildren
  '/_protected/accept-invitation/$id': typeof ProtectedAcceptInvitationIdRoute
  '/_protected/_org/': typeof ProtectedOrgIndexRoute
  '/_protected/_org/catalog/$id': typeof ProtectedOrgCatalogIdRoute
  '/_protected/_org/chat/$chatId': typeof ProtectedOrgChatChatIdRoute
  '/_protected/_org/chat/new': typeof ProtectedOrgChatNewRoute
  '/_protected/_org/settings/general': typeof ProtectedOrgSettingsGeneralRoute
  '/_protected/_org/settings/members': typeof ProtectedOrgSettingsMembersRoute
  '/_protected/_org/catalog/': typeof ProtectedOrgCatalogIndexRoute
  '/_protected/_org/settings/': typeof ProtectedOrgSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/settings'
    | '/accept-invitation/$id'
    | '/catalog/$id'
    | '/chat/$chatId'
    | '/chat/new'
    | '/settings/general'
    | '/settings/members'
    | '/catalog/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/onboarding'
    | '/accept-invitation/$id'
    | '/catalog/$id'
    | '/chat/$chatId'
    | '/chat/new'
    | '/settings/general'
    | '/settings/members'
    | '/catalog'
    | '/settings'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/reset-password'
    | '/_auth/signup'
    | '/_protected/_org'
    | '/_protected/onboarding'
    | '/_protected/_org/settings'
    | '/_protected/accept-invitation/$id'
    | '/_protected/_org/'
    | '/_protected/_org/catalog/$id'
    | '/_protected/_org/chat/$chatId'
    | '/_protected/_org/chat/new'
    | '/_protected/_org/settings/general'
    | '/_protected/_org/settings/members'
    | '/_protected/_org/catalog/'
    | '/_protected/_org/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/_org': {
      id: '/_protected/_org'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedOrgRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/onboarding': {
      id: '/_protected/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof ProtectedOnboardingRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_org/': {
      id: '/_protected/_org/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedOrgIndexRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/_org/settings': {
      id: '/_protected/_org/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedOrgSettingsRouteRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/accept-invitation/$id': {
      id: '/_protected/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof ProtectedAcceptInvitationIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_org/catalog/': {
      id: '/_protected/_org/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof ProtectedOrgCatalogIndexRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/_org/catalog/$id': {
      id: '/_protected/_org/catalog/$id'
      path: '/catalog/$id'
      fullPath: '/catalog/$id'
      preLoaderRoute: typeof ProtectedOrgCatalogIdRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/_org/chat/$chatId': {
      id: '/_protected/_org/chat/$chatId'
      path: '/chat/$chatId'
      fullPath: '/chat/$chatId'
      preLoaderRoute: typeof ProtectedOrgChatChatIdRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/_org/chat/new': {
      id: '/_protected/_org/chat/new'
      path: '/chat/new'
      fullPath: '/chat/new'
      preLoaderRoute: typeof ProtectedOrgChatNewRouteImport
      parentRoute: typeof ProtectedOrgRoute
    }
    '/_protected/_org/settings/': {
      id: '/_protected/_org/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedOrgSettingsIndexRouteImport
      parentRoute: typeof ProtectedOrgSettingsRouteRoute
    }
    '/_protected/_org/settings/general': {
      id: '/_protected/_org/settings/general'
      path: '/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof ProtectedOrgSettingsGeneralRouteImport
      parentRoute: typeof ProtectedOrgSettingsRouteRoute
    }
    '/_protected/_org/settings/members': {
      id: '/_protected/_org/settings/members'
      path: '/members'
      fullPath: '/settings/members'
      preLoaderRoute: typeof ProtectedOrgSettingsMembersRouteImport
      parentRoute: typeof ProtectedOrgSettingsRouteRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedOrgSettingsRouteRouteChildren {
  ProtectedOrgSettingsGeneralRoute: typeof ProtectedOrgSettingsGeneralRoute
  ProtectedOrgSettingsMembersRoute: typeof ProtectedOrgSettingsMembersRoute
  ProtectedOrgSettingsIndexRoute: typeof ProtectedOrgSettingsIndexRoute
}

const ProtectedOrgSettingsRouteRouteChildren: ProtectedOrgSettingsRouteRouteChildren =
  {
    ProtectedOrgSettingsGeneralRoute: ProtectedOrgSettingsGeneralRoute,
    ProtectedOrgSettingsMembersRoute: ProtectedOrgSettingsMembersRoute,
    ProtectedOrgSettingsIndexRoute: ProtectedOrgSettingsIndexRoute,
  }

const ProtectedOrgSettingsRouteRouteWithChildren =
  ProtectedOrgSettingsRouteRoute._addFileChildren(
    ProtectedOrgSettingsRouteRouteChildren,
  )

interface ProtectedOrgRouteChildren {
  ProtectedOrgSettingsRouteRoute: typeof ProtectedOrgSettingsRouteRouteWithChildren
  ProtectedOrgIndexRoute: typeof ProtectedOrgIndexRoute
  ProtectedOrgCatalogIdRoute: typeof ProtectedOrgCatalogIdRoute
  ProtectedOrgChatChatIdRoute: typeof ProtectedOrgChatChatIdRoute
  ProtectedOrgChatNewRoute: typeof ProtectedOrgChatNewRoute
  ProtectedOrgCatalogIndexRoute: typeof ProtectedOrgCatalogIndexRoute
}

const ProtectedOrgRouteChildren: ProtectedOrgRouteChildren = {
  ProtectedOrgSettingsRouteRoute: ProtectedOrgSettingsRouteRouteWithChildren,
  ProtectedOrgIndexRoute: ProtectedOrgIndexRoute,
  ProtectedOrgCatalogIdRoute: ProtectedOrgCatalogIdRoute,
  ProtectedOrgChatChatIdRoute: ProtectedOrgChatChatIdRoute,
  ProtectedOrgChatNewRoute: ProtectedOrgChatNewRoute,
  ProtectedOrgCatalogIndexRoute: ProtectedOrgCatalogIndexRoute,
}

const ProtectedOrgRouteWithChildren = ProtectedOrgRoute._addFileChildren(
  ProtectedOrgRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedOrgRoute: typeof ProtectedOrgRouteWithChildren
  ProtectedOnboardingRoute: typeof ProtectedOnboardingRoute
  ProtectedAcceptInvitationIdRoute: typeof ProtectedAcceptInvitationIdRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedOrgRoute: ProtectedOrgRouteWithChildren,
  ProtectedOnboardingRoute: ProtectedOnboardingRoute,
  ProtectedAcceptInvitationIdRoute: ProtectedAcceptInvitationIdRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
