/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ../../packages/env/src/env.d.ts` (hash: 95c77f0959698c03287efe5f9124d9d1)
interface __BaseEnv_Env {
	DB: D1Database;
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	RESEND_API_KEY: string;
	EMAIL_SENDER: string;
	MOCK_SEND_EMAIL: string;
	ORG_CHAT_PROVIDER: string;
	ZAI_API_KEY: string;
	LOADER: WorkerLoader;
	FETCH_ALLOWED_HOSTS: "";
	OrgAgent: DurableObjectNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FETCH_ALLOWED_HOSTS">> {}
}
