/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-file=.dev.vars.example --include-runtime=false ../../packages/env/src/env.d.ts` (hash: 787a4ba1e2129c33313a1ba2c9e53561)
interface __BaseEnv_Env {
	DB: D1Database;
	LOADER: WorkerLoader;
	FETCH_ALLOWED_HOSTS: "";
	BETTER_AUTH_SECRET: string;
	BETTER_AUTH_URL: string;
	RESEND_API_KEY: string;
	EMAIL_SENDER: string;
	MOCK_SEND_EMAIL: string;
	ORG_CHAT_PROVIDER: string;
	ORG_CHAT_MODEL: string;
	CF_ACCOUNT_ID: string;
	WORKERS_AI_API_TOKEN: string;
	OPENAI_COMPATIBLE_BASE_URL: string;
	OPENAI_COMPATIBLE_API_KEY: string;
	OrgAgent: DurableObjectNamespace;
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "FETCH_ALLOWED_HOSTS" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "RESEND_API_KEY" | "EMAIL_SENDER" | "MOCK_SEND_EMAIL" | "ORG_CHAT_PROVIDER" | "ORG_CHAT_MODEL" | "CF_ACCOUNT_ID" | "WORKERS_AI_API_TOKEN" | "OPENAI_COMPATIBLE_BASE_URL" | "OPENAI_COMPATIBLE_API_KEY">> {}
}
